Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"

  config.vm.define "vm4" do |vm4|

    vm4.vm.network "private_network", ip: "10.0.0.101"

  end

  config.vm.provider "virtualbox" do |vb|

    vb.memory = "512"
    vb.cpus = 1
    
  end
  
  PUBLIC_KEY = File.read(File.expand_path('~/.ssh/id_rsa.pub')).strip

  config.vm.provision "shell", inline: <<-SHELL

    apt-get -y update
    apt-get -y upgrade
    apt-get -y autoremove
    apt-get -y install -y vim
    echo "#{PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys

  SHELL
end
