---

- name: Copy files.
  copy:
    src: mattermost
    dest: .
  become: yes

- name: Setup Beats.
  include_tasks:
    file: ../../beats/tasks/main.yml

- name: Prepare environment.
  include_tasks:
    file: setup.yml

- name: Start containers.
  community.docker.docker_compose:
    project_src: mattermost
    build: yes
    state: present
    remove_orphans: yes
  register: output
  become: yes