---

- name: Creates directory
  file:
    path: ./mattermost/volumes/app/mattermost/{{ item }}
    state: directory
  with_items: 
    - data
    - logs
    - config
    - plugins
    - client-plugins
  become: yes

- name: Recursively change ownership of directory ./mattermost/app
  file:
    path: mattermost/app
    state: directory
    recurse: yes
    owner: "2000"
    group: "2000"
  become: yes

- name: Recursively change ownership of directory ./mattermost/web
  file:
    path: mattermost/web
    state: directory
    recurse: yes
    owner: "2000"
    group: "2000"
  become: yes

- name: Recursively change ownership of directory ./mattermost/volumes
  file:
    path: mattermost/volumes
    state: directory
    recurse: yes
    owner: "2000"
    group: "2000"
  become: yes

- name: Set app bash scripts executable permissions
  file:
    path: ./mattermost/app/entrypoint.sh
    state: file
    mode: '0755'
  become: yes

- name: Set web bash scripts executable permissions
  file:
    path: ./mattermost/web/entrypoint.sh
    state: file
    mode: '0755'
  become: yes