---
- name: Update cache.
  apt: 
    update_cache: yes
    allow_unauthenticated: yes
  become: yes

- name: Install.
  include_tasks: 
    file: install.yml

- name: Ensure group "docker" exists with correct gid
  group:
    name: docker
    state: present

- name: Add user to docker group.
  user:
    state: present
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: yes
  become: yes
  