---

- name: Copy files docker-pg-slave.
  copy:
    src: docker-pg-slave
    dest: .
  become: yes

- name: Start containers docker-pg-slave.
  community.docker.docker_compose:
    project_src: docker-pg-slave
    build: yes
    state: present
    remove_orphans: yes
  register: output
  become: yes
