---
- name: Copy beat files.
  copy:
    src: elasticstack/beats/
    dest: mattermost/beats/
  become: yes

- name: Prepare configuration files.
  shell: chown root mattermost/beats/*/*.yml && chmod go-w mattermost/beats/*/*.yml
  become: yes

- name: Setup heartbeat indexes.
  shell: cd ~/mattermost && \
         docker-compose run heartbeat setup && \
         cd ~
