---

- name: Change working directory.
  shell: cd ~

- name: Copy files.
  copy:
    src: elasticstack/kibana
    dest: elasticstack/

- name: Copy docker-compose file.
  copy:
    src: elasticstack/docker-compose.yml
    dest: elasticstack/

- name: Start container.
  community.docker.docker_compose:
    project_src: elasticstack
    build: yes
    state: present
    remove_orphans: yes
    services: kibana
  register: output
  become: yes