version: "3"
services:
        web:
                image: my/tomcat
                deploy:
                        replicas: 2
                ports:
                        - "8080:8080"                                 