- name: Mattermost Web Server Provision

  hosts: web_server

  tasks:
    - name: Download Mattermost Web Server
      get_url:
        url: https://releases.mattermost.com/5.29.1/mattermost-5.29.1-linux-amd64.tar.gz
        dest: ~/mattermost-5.29.1-linux-amd64.tar.gz

    - name: Unpack Mattermost
      unarchive:
          src: ~/mattermost-5.29.1-linux-amd64.tar.gz
          dest: ~/
          remote_src: yes

    - name: Remove packed files
      file:
        path: ~/mattermost-5.29.1-linux-amd64.tar.gz
        dest: /opt
        state: absent

    - name: Add a user at the operating system level
      user:
        name: admin
        