Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"
  
  config.vm.define "web_server" do |web_server|

    web_server.vm.network "private_network", ip: "10.0.0.101"

  end

  config.vm.provider "virtualbox" do |vb|

    vb.memory = "2048"
    vb.cpus = 1

  end

  config.vm.provision :ansible do |ansible|

      ansible.playbook = "playbook.yml"

  end

  PUBLIC_KEY = File.read(File.expand_path('~/.ssh/id_rsa.pub')).strip

  config.vm.provision "shell", inline: <<-SHELL
    
    apt-get -y update 
    apt-get -y upgrade 
    apt-get -y autoremove 
    apt-get install -y vim

    echo "#{PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys

  SHELL

end