version: "3"

services:

  db:
    build: ./slave
    environment:
      - POSTGRES_USER=mmuser
      - POSTGRES_PASSWORD=mmuser_password
      - POSTGRES_DB=mattermost
      - PG_REP_USER=mmuser_rep
      - PG_REP_PASSWORD=mmuser_password
      - PG_MASTER_HOST=${MM_DB_MASTER}
      - PG_BEATS_USER=beats
      - PG_BEATS_PASSWORD=beats_password
    network_mode: host
