
Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"
  
  config.vm.define "vm1" do |vm1|

    vm1.vm.network "private_network", ip: "10.0.0.101"

  end

  config.vm.define "vm2" do |vm2|

    vm2.vm.network "private_network", ip: "10.0.0.102"

  end

  config.vm.provider "virtualbox" do |vb|

    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the specs on the VM:
    vb.memory = "512"
    vb.cpus = 1

  end

  PUBLIC_KEY = File.read(File.expand_path('~/.ssh/id_rsa.pub')).strip

  config.vm.provision "shell", inline: <<-SHELL
    
    apt-get -y update 
    apt-get -y upgrade 
    apt-get -y autoremove 
    apt-get install -y vim

    echo "#{PUBLIC_KEY}" >> /home/vagrant/.ssh/authorized_keys

  SHELL

end
